# GENERATED by scripts/formula.sh from the v0.1.1 release's SHA256SUMS. Do not edit: the next
# release rewrites it.
class Tinybrains < Formula
  desc "Play, check and watch TinyBrains matches on a laptop"
  homepage "https://github.com/Tiny-Brains/cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    depends_on arch: :arm64
    depends_on macos: :tahoe

    url "https://github.com/Tiny-Brains/cli/releases/download/v0.1.1/tinybrains-aarch64-apple-darwin.tar.gz"
    sha256 "c45fb73c3a2e3c00435a9932bdc83a135b370fd459b80b9c6d9ba9a32a721374"
  end

  on_linux do
    on_arm do
      url "https://github.com/Tiny-Brains/cli/releases/download/v0.1.1/tinybrains-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f29ef1e434dc2832732644c29132af6bba4511e9d33b68c1f845d83a4cffe5b5"
    end
    on_intel do
      url "https://github.com/Tiny-Brains/cli/releases/download/v0.1.1/tinybrains-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1f57cafc8f0ce2de7062ec5c7a15b9d4aa0c29834caeaa1494372774bbad4ab0"
    end
  end

  def install
    bin.install "tinybrains"
  end

  test do
    assert_match "tinybrains #{version}", shell_output("#{bin}/tinybrains --version")
  end
end
