# GENERATED by scripts/formula.sh from the v0.4.0 release's SHA256SUMS. Do not edit: the next
# release rewrites it.
class Tinybrains < Formula
  desc "Play, check and watch TinyBrains matches on a laptop"
  homepage "https://github.com/Tiny-Brains/cli"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    depends_on arch: :arm64
    depends_on macos: :tahoe

    url "https://github.com/Tiny-Brains/cli/releases/download/v0.4.0/tinybrains-aarch64-apple-darwin.tar.gz"
    sha256 "3afef001f5b731595f55a8b52b56568428d07df12dd65a301e5f080687c6f6a0"
  end

  on_linux do
    on_arm do
      url "https://github.com/Tiny-Brains/cli/releases/download/v0.4.0/tinybrains-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "d138e4e53c6d081dcb41566846eb5e6084f6ab4da68a93bb6a38661055669147"
    end
    on_intel do
      url "https://github.com/Tiny-Brains/cli/releases/download/v0.4.0/tinybrains-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "278874ec81ded3497786e5c51cf221b880639ba9ab300d53b10db97403198f27"
    end
  end

  def install
    bin.install "tinybrains"
  end

  test do
    assert_match "tinybrains #{version}", shell_output("#{bin}/tinybrains --version")
  end
end
