# GENERATED by scripts/formula.sh from the v0.1.0 release's SHA256SUMS. Do not edit: the next
# release rewrites it.
class Tinybrains < Formula
  desc "Play, check and watch TinyBrains matches on a laptop"
  homepage "https://github.com/Tiny-Brains/cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    depends_on arch: :arm64
    depends_on macos: :tahoe

    url "https://github.com/Tiny-Brains/cli/releases/download/v0.1.0/tinybrains-aarch64-apple-darwin.tar.gz"
    sha256 "49c360bc267b50562947c993109930838f67e17fc4c330084bf1726a1f53bba4"
  end

  on_linux do
    on_arm do
      url "https://github.com/Tiny-Brains/cli/releases/download/v0.1.0/tinybrains-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "aa67fa2c30ef857e3800965ee795e89774d31575436360d1526e4ce637b73382"
    end
    on_intel do
      url "https://github.com/Tiny-Brains/cli/releases/download/v0.1.0/tinybrains-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f30fcb7007439ffb63954fc084b3a7cf0a7c2968a7707202587dc71261329d16"
    end
  end

  def install
    bin.install "tinybrains"
  end

  test do
    assert_match "tinybrains #{version}", shell_output("#{bin}/tinybrains --version")
  end
end
