#!/bin/sh
# Print the Homebrew formula for one release, from that release's SHA256SUMS.
#
#   scripts/formula.sh 0.1.0 SHA256SUMS > Formula/tinybrains.rb
#
# The release workflow runs this against the SHA256SUMS it DOWNLOADS from the published release,
# never against the files it built, so the formula can only name bytes a user can actually fetch.
#
# THE TAP IS THIS REPOSITORY. There is no homebrew-tap repository to keep in step: `Formula/` here
# is the tap, and `brew tap tiny-brains/cli https://github.com/Tiny-Brains/cli` reads it. The URL is
# required only because the repository is not named `homebrew-cli`.
set -eu

if [ $# -ne 2 ]; then
  echo "usage: scripts/formula.sh <version> <SHA256SUMS>" >&2
  exit 2
fi
version=$1
sums=$2
base="https://github.com/Tiny-Brains/cli/releases/download/v${version}"

# One target's archive digest, or a refusal naming the file that is missing: a formula with an
# empty sha256 installs nothing and says only that a checksum did not match.
sum() {
  file="tinybrains-$1.tar.gz"
  hex=$(awk -v f="$file" '$2 == f || $2 == "*" f { print $1 }' "$sums")
  case "$hex" in
    [0-9a-f]*) [ ${#hex} -eq 64 ] && { echo "$hex"; return; } ;;
  esac
  echo "formula.sh: no sha256 for $file in $sums" >&2
  exit 1
}

mac_arm=$(sum aarch64-apple-darwin)
mac_intel=$(sum x86_64-apple-darwin)
linux_arm=$(sum aarch64-unknown-linux-gnu)
linux_intel=$(sum x86_64-unknown-linux-gnu)

cat <<RUBY
# GENERATED by scripts/formula.sh from the v${version} release's SHA256SUMS. Do not edit: the next
# release rewrites it.
class Tinybrains < Formula
  desc "Play, check and watch TinyBrains matches on a laptop"
  homepage "https://github.com/Tiny-Brains/cli"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base}/tinybrains-aarch64-apple-darwin.tar.gz"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "${base}/tinybrains-x86_64-apple-darwin.tar.gz"
      sha256 "${mac_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/tinybrains-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/tinybrains-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "tinybrains"
  end

  test do
    assert_match "tinybrains #{version}", shell_output("#{bin}/tinybrains --version")
  end
end
RUBY
